version: "3.3"

services:
  mongo:
    image: mongo
    container_name: mongo-testing
    environment:
      MONGODB_DATABASE: testing-db
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
