version: '3.0'
services:
  db:
    image: mongo:5.0.0
    container_name: testing-db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: testing-db
    volumes:
      - ./mongo:/data/db