version: "3.3"

services:
  mongo:
    image: mongo
    container_name: mongo-testing
    environment:
      MONGODB_DATABASE: testing-db
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
  locust-master:
    build:
      context: .
      dockerfile: locust/Dockerfile
    container_name: locust-master
    ports:
      - "8089:8089"
    command: "--host=https://e24d-179-6-160-198.ngrok.io --master"
  locust-slave:
    depends_on:
      - locust-master
    build:
      context: .
      dockerfile: locust/Dockerfile
    command: "--host=https://e24d-179-6-160-198.ngrok.io --master-host=locust-master --slave"
